### ISSUE TITLE
Unclear indexing in s

### ISSUE THREAD

**Issue by dmelani** [microsoft/PQCrypto-LWEKE#10]
https://github.com/microsoft/PQCrypto-LWEKE/blob/d5bbd0417ba111b08a959c0042a1dcc65fb14a89/src/frodo_macrify_reference.c#L59

It seems like you are indexing s as if it is in column major order. Is this really correct?

**Comment by patricklonga** [comment]
Maybe you're asking because that's not the way it's specified in the specs document? If this is the case, we are aware of the issue and will post an update soon.

**Comment by dmelani** [comment]
Yes that's why I asked. Thank you for the clarification.
