### ISSUE TITLE
Measure of level of security

### ISSUE THREAD

**Issue by sarabjeetsingh007** [microsoft/PQCrypto-LWEKE#17]
Documentation says "FrodoKEM-640-AES: matching the post-quantum security of AES128".  
Does the algorithm describe a measure of security level?
If I were to make changes to the code, is there a metric that I can verify against in order to state my algorithm to be secure?
Or is passing against the Known Answer Tests the only check?

**Comment by dstebila** [comment]
The argument for the security of FrodoKEM is given in the specification document at https://frodokem.org/.  

We do not recommend that you make changes to the algorithm design or parameters.  As for the security of a new implementation, one should be very careful in implementing cryptographic algorithms to avoid implementation flaws that could undermine security.  Wherever possible you should make use of existing high-quality vetted implementations in reputable libraries.

**Comment by sarabjeetsingh007** [comment]
Thanks. Looking further into the spec sheet.
Before closing this, is Known Answer Tests a check for the correctness of algorithm?

**Comment by dstebila** [comment]
It is an indicator towards correctness, but it is not complete.  It is possible to implement something that passes the KATs but is not correct, and it is possible to implement something that is correct but does not pass the KATs.
