### ISSUE TITLE
Unclear why PARAMS_NBAR has be a multiple of 8

### ISSUE THREAD

**Issue by sarabjeetsingh007** [microsoft/PQCrypto-LWEKE#18]
Hi,
I did not understand the purpose of PARAMS_NBAR in the reference code, and why should it be a multiple of 8. 
Also, Regev'05 did not use PARAMS_NBAR parameter in their LWE proposal.

Can you help me understand it?

**Comment by dstebila** [comment]
n-bar is a matrix dimension, and you can see where it is used in Algorithms 9, 10, 11 of https://frodokem.org/files/FrodoKEM-specification-20200930.pdf.
