### ISSUE TITLE
round() makes a mistake

### ISSUE THREAD

**Issue by Jul1anWang** [microsoft/PQCrypto-LWEKE#26]
Hi,

When I used the python implementation to run an experiment, I found an error in [decode method ](https://github.com/microsoft/PQCrypto-LWEKE/blob/master/python3/frodokem.py#L324)when  E''' = 2^(D-B-1). It should make a decryption failure, but that didn't happen! Like this,

`round(51200*16/65536)=12 #51200*16/65536=12.5`

I found that the reason is  **round()** returns a mistake answer sometimes because the peoperty of float number .
So, why not replace 
`round(a)`
 with
`math.floor(a+0.5)`

**Comment by dstebila** [comment]
Thanks Jian. I've proposed a fix in #27.
