### ISSUE TITLE
enable PQCrypto-LWEKE on s390x 

### ISSUE THREAD

**Issue by poojashyam2k** [microsoft/PQCrypto-LWEKE#32]
The PQCrypto-LWEKE library has been tested on s390x architecture with a configuration very similar to PPC. On initial exploration, it looks like the PPC configurations can work efficiently on s390x. The goal is to try out the Power PC configuration on s390x, build and test and make the changes needed to enable it.

**Comment by dstebila** [comment]
We do test FrodoKEM in liboqs (which is derived from PQCrypto-LWEKE) on s390x via [Travis CI](https://github.com/open-quantum-safe/liboqs/blob/main/.travis.yml).

**Comment by poojashyam2k** [comment]
That's interesting. I was testing it the same way. In this case too, just selecting Power PC in the makefile when the architecture is s390x should do it. It could help with use cases where we want to directly work/experiment with the library?

**Comment by patricklonga** [comment]
Support for s390x has been added. Thanks for the suggestion.
