### ISSUE TITLE
CDF table of Frodo 1344 different from specification

### ISSUE THREAD

**Issue by mekhall** [microsoft/PQCrypto-LWEKE#35]
The CDF table in frodo1344.c has 7 entries amongst which one is 32765. 

I noted that in the latest specification, table A.4 has only six elements. 32765 is missing.

Is that a typo in the specification or the implementation? (Or have I misunderstood something?)

Also in noise.c where the CDF table is used:

for (j = 0; j < (unsigned int)(CDF_TABLE_LEN - 1); j++) {

the for loop does not use the last element of the CDF table. Is that intentional?

**Comment by patricklonga** [comment]
It's a typo in Table A.4 in the specification. For FrodoKEM-1344, entry Tx(5) should be 32765 and entry Tx(6) should be 32767. This will be corrected.

And indeed, the last element in the CDF table is never accessed in the implementation.
